### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by JokinYang** [YeungKC/Hakuba#157]
Hi, YeungKC! 
Hakuba is a really useful repo for the one who want to build their own blog without a server. Thanks for your efforts!
When I used it, I found it can not render mathjax field like `$(ax^2 + bx + c = 0)$` which has been added in Github Markdown at 2022-05-19,[Math support in markdown](https://github.blog/2022-05-19-math-support-in-markdown/). This is necesssary for some people to write the blog. So I file a issue to find if there is an easy way to do it.

**Comment by YeungKC** [comment]
I found a related issue https://github.com/pngwn/MDsveX/issues/302
